# Generated by Django 5.0.2 on 2024-02-16 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postulante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_laboral', models.FileField(blank=True, upload_to='uploads')),
                ('descripcion_laborar', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='postulante',
            name='calificacion_postulante',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='edad_postulante',
            field=models.IntegerField(),
        ),
    ]
