# Generated by Django 5.0.2 on 2024-02-17 03:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detalle_postulante_postulados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=144)),
                ('telefono_ciudad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('email_ciudad', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Detallepostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia_laboral', models.TextField(blank=True, null=True)),
                ('curso_laboral', models.CharField(max_length=255)),
                ('descripcion_laboral', models.TextField(blank=True, null=True)),
                ('idioma_laboral', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleo', models.CharField(max_length=144)),
                ('descripcion_empleo', models.TextField(blank=True, null=True)),
                ('fecha_empleo', models.DateTimeField(default=django.utils.timezone.now)),
                ('area_empleo', models.CharField(max_length=200)),
                ('modalidad_empleo', models.CharField(max_length=200)),
                ('tiempo_empleo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('id_ciudad_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudad', to='app.ciudad')),
            ],
        ),
        migrations.DeleteModel(
            name='Detalle_Postulante',
        ),
        migrations.RenameField(
            model_name='postulados',
            old_name='fecha_postulacion',
            new_name='fecha_postulado',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='calificacion_postulante',
        ),
        migrations.AddField(
            model_name='postulados',
            name='estado_postulado',
            field=models.CharField(default=1, max_length=144),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulados',
            name='id_postulados_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulado', to='app.postulante'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='ciudad_postulante',
            field=models.CharField(default=1, max_length=144),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulante',
            name='genero_postulante',
            field=models.CharField(default=1, max_length=144),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulante',
            name='direccion_postulante',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulante',
            name='edad_postulante',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='email_postulante',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulante',
            name='telefono_postulante',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='detallepostulante',
            name='id_postulante_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulante', to='app.postulante'),
        ),
        migrations.AddField(
            model_name='postulados',
            name='id_empleo_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleo', to='app.empleo'),
        ),
    ]
